---
title: "problem set 1"
author: "r11323035 俞凱翔"
date: "2023-02-20"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

```{r message=FALSE}
library(tidyverse)
library(nleqslv)
library(CVXR)
library(NMOF)
library(maxLik)
library(readxl)
library(msm)
library(car)
library(bootstrap)
```

Question 1


#Q1-1
```{r}
set.seed(888)
N <- 400
beta1 <- 0.5
beta2 <- -0.5

data <- data.frame(
    "u1" = -log(-log(runif(N, min = 0, max = 1))),
    "u2" = -log(-log(runif(N, min = 0, max = 1))),
    "x1" = rnorm(N, mean = 0, sd = 1),
    "x2" = rchisq(N, df = 1)) %>%
  mutate(., y = ifelse(beta1 * x1 + u1 > beta2 * x2 + u2, 1, 0))
```


#Q1-2
```{r}
ll.l <- function(x, sample = data){
  beta.1 <- x[1]
  beta.2 <- x[2]
  -sum(sample$y * log(plogis(sample$x1 * beta.1 - sample$x2 * beta.2)) + 
         (1 - sample$y) * log(1 - plogis(sample$x1 * beta.1 - sample$x2 * beta.2)))
}
```


#Q1-3
```{r}
tor_err <- 10 ^ -4
err <- 1000000
times <- 0
min_ll.l <- 10000
b_star <- c(0, 0)

while (tor_err < err & times < 100){
  
  b1_grid <- seq((b_star[1] - 5) / 2 ^ times, (b_star[1] + 5) / 2 ^ times, length.out = 10)
  b2_grid <- seq((b_star[2] - 5) / 2 ^ times, (b_star[2] + 5) / 2 ^ times, length.out = 10)
  
  for (b1 in b1_grid) {
    for (b2 in b2_grid) {
      b <- c(b1, b2)
      if (!is.nan(ll.l(b)) & ll.l(b) < min_ll.l){
        err <- max(abs(b_star - b))
        b_star <- c(b1, b2)
        min_ll.l <- ll.l(b)
      }
    }
  }
  times <- times + 1
}
b_star

#using package, the default method is"Nelder-Mead".
mle.L <- optim(c(-5, 5), ll.l, hessian = T)
mle.L$par
```


#Q1-4
```{r}
set.seed(999)
R <- 100

#generate samples
sample_100 <- list()
for (i in 1: R) {
  data <- data.frame(
    "u1" = -log(-log(runif(N, min = 0, max = 1))),
    "u2" = -log(-log(runif(N, min = 0, max = 1))),
    "x1" = rnorm(N, mean = 0, sd = 1),
    "x2" = rchisq(N, df = 1)) %>%
    mutate(., y = ifelse(beta1 * x1 + u1 > beta2 * x2 + u2, 1, 0))
  
  sample_100[i] <- list(data)
}

#estimate the samples with Nelder-Mead to maximize the log likelihood func.
mle_100 <- NULL
for (j in 1: R) {
  
  #generate a ML func. with default = sample_100[[j]]
  mle_fun <- function(x, sample = sample_100[[j]]){
    beta.1 <- x[1]
    beta.2 <- x[2]
    -sum(sample$y * log(plogis(sample$x1 * beta.1 - sample$x2 * beta.2)) + 
         (1 - sample$y) * log(1 - plogis(sample$x1 * beta.1 - sample$x2 * beta.2)))}
  
  #use the optim function, the default method is"Nelder-Mead". 
  mle.l <- optim(par = c(-5, 5), mle_fun, hessian = T)
  mle_100 <- rbind(mle_100, mle.l$par)
}

#mean and variance
apply(mle_100, MARGIN = 2, FUN = mean)
var(mle_100)
```


Question 2
```{r}
cps09mar <- read_excel("cps09mar.xlsx")
cps09mar_black <- cps09mar %>%
  mutate(., married = ifelse(marital < 4, 1, 0),
         Black = ifelse(race == 2, 1, 0)) %>%
  subset(., Black == 1) %>%
  subset(., region == 2) %>%
  subset(., female == 1)
```


#Q2-1
```{r}
logit_married <- glm(married ~ age + I(age ^ 2) + education, data = cps09mar_black, family = "binomial")
logit_summary <- summary(logit_married)
logit_summary
```


#Q2-2
```{r}
set.seed(123)
sample_coef <- NULL

for (i in 1: 100) {
  sample_d <- cps09mar_black[sample(1: nrow(cps09mar_black), nrow(cps09mar_black), replace = TRUE), ]
  logit_bootstrp <- glm(married ~ age + I(age ^ 2) + education, data = sample_d, family = "binomial")
  sample_coef <- rbind(sample_coef, summary(logit_bootstrp)$coefficient[,1])
}
list(mean = apply(sample_coef, MARGIN = 2, FUN = mean), 
     sd   = apply(sample_coef, MARGIN = 2, FUN =sd))

#by package: "car"
fit_b <- Boot(logit_married, R = 100)
summary(fit_b)
```


#Q2-3
```{r}
age_mean <- logit_summary$coefficients[2: 3]
age_cov_matrix <- logit_summary$cov.unscaled[2: 3, 2: 3] 

#estimate theta_hat
-age_mean[1] / (2 * age_mean[2])

#standard error
deltamethod(~ -x1 / (2 * x2), age_mean, age_cov_matrix)
```


#Q2-4
```{r}
#use the coefficients generated in Q2-2.
theta <- -sample_coef[, 2] / (2 * sample_coef[, 3])

list(theta_hat = mean(theta),
     theta_hat_sd = sd(theta))
```